/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_8 (
    output reg [7:0] io_led2,
    input [23:0] io_dip
  );
  
  
  
  reg [7:0] result3;
  
  wire [8-1:0] M_reverse_io_led2;
  reverse_16 reverse (
    .io_dip(io_dip),
    .io_led2(M_reverse_io_led2)
  );
  
  always @* begin
    result3 = 8'h00;
    
    case (io_dip[16+0+3-:4])
      4'h8: begin
        result3 = io_dip[0+7-:8] & io_dip[8+7-:8];
      end
      4'he: begin
        result3 = io_dip[0+7-:8] | io_dip[8+7-:8];
      end
      3'h6: begin
        result3 = io_dip[0+7-:8] ^ io_dip[8+7-:8];
      end
      4'ha: begin
        result3 = io_dip[0+7-:8];
      end
      3'h5: begin
        result3 = M_reverse_io_led2;
      end
    endcase
    io_led2 = result3[0+7-:8];
  end
endmodule
