/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_3 (
    input clk,
    input rst,
    output reg [7:0] io_led2,
    input [23:0] io_dip
  );
  
  
  
  reg [8:0] result;
  
  reg [7:0] result2;
  
  reg z;
  
  reg v;
  
  reg n;
  
  always @* begin
    if (io_dip[16+0+0-:1] == 1'h0) begin
      result = io_dip[8+7-:8] + io_dip[0+7-:8];
    end else begin
      result = io_dip[8+7-:8] - io_dip[0+7-:8];
    end
    z = !((&result[0+7-:8]));
    v = io_dip[0+7+0-:1] * io_dip[8+7+0-:1] * !result[7+0-:1] + !io_dip[0+7+0-:1] * !io_dip[8+7+0-:1] * result[7+0-:1];
    n = result[7+0-:1];
    result2 = 8'h00;
    
    case (io_dip[16+1+1-:2])
      1'h1: begin
        result2 = {7'h00, z};
      end
      2'h2: begin
        result2 = {7'h00, v ^ n};
      end
      2'h3: begin
        result2 = {7'h00, z + v ^ n};
      end
      1'h0: begin
        result2 = 8'h00;
      end
    endcase
    io_led2 = result2[0+7-:8];
  end
endmodule
