/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_7 (
    output reg [7:0] io_led2,
    input [23:0] io_dip
  );
  
  
  
  reg [7:0] result;
  
  reg z;
  
  reg v;
  
  reg n;
  
  wire [8-1:0] M_add_io_led2;
  wire [1-1:0] M_add_z;
  wire [1-1:0] M_add_v;
  wire [1-1:0] M_add_n;
  add_6 add (
    .io_dip(io_dip),
    .io_led2(M_add_io_led2),
    .z(M_add_z),
    .v(M_add_v),
    .n(M_add_n)
  );
  
  always @* begin
    z = M_add_z;
    v = M_add_v;
    n = M_add_n;
    result = 8'h00;
    
    case (io_dip[16+1+1-:2])
      1'h1: begin
        result = {7'h00, z};
      end
      2'h2: begin
        result = {7'h00, v ^ n};
      end
      2'h3: begin
        result = {7'h00, z | (v ^ n)};
      end
      1'h0: begin
        result = 8'h00;
      end
    endcase
    io_led2 = result[0+7-:8];
  end
endmodule
