/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module reverse_16 (
    input [23:0] io_dip,
    output reg [7:0] io_led2
  );
  
  
  
  always @* begin
    io_led2[0+0-:1] = io_dip[0+7+0-:1];
    io_led2[1+0-:1] = io_dip[0+6+0-:1];
    io_led2[2+0-:1] = io_dip[0+5+0-:1];
    io_led2[3+0-:1] = io_dip[0+4+0-:1];
    io_led2[4+0-:1] = io_dip[0+3+0-:1];
    io_led2[5+0-:1] = io_dip[0+2+0-:1];
    io_led2[6+0-:1] = io_dip[0+1+0-:1];
    io_led2[7+0-:1] = io_dip[0+0+0-:1];
  end
endmodule
