/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shift_6 (
    output reg [7:0] io_led2,
    input [23:0] io_dip
  );
  
  
  
  reg [7:0] result4;
  
  always @* begin
    result4 = 8'h00;
    
    case (io_dip[16+0+1-:2])
      1'h1: begin
        result4 = io_dip[0+7-:8] >> io_dip[8+0+2-:3];
      end
      2'h3: begin
        result4 = $signed(io_dip[0+7-:8]) >>> io_dip[8+0+2-:3];
      end
      1'h0: begin
        result4 = io_dip[0+7-:8] << io_dip[8+0+2-:3];
      end
    endcase
    io_led2 = result4[0+7-:8];
  end
endmodule
