/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module add_3 (
    output reg [7:0] io_led2,
    input [23:0] io_dip,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [8:0] result;
  
  always @* begin
    if (io_dip[16+0+0-:1] == 1'h0) begin
      result = io_dip[8+7-:8] + io_dip[0+7-:8];
    end else begin
      result = io_dip[8+7-:8] - io_dip[0+7-:8];
    end
    io_led2 = result[0+7-:8];
    if (result == 1'h0) begin
      z = 1'h1;
    end else begin
      z = 1'h0;
    end
    v = (io_dip[0+7+0-:1] && io_dip[8+7+0-:1] && (!result[7+0-:1])) || ((!io_dip[0+7+0-:1]) && (!io_dip[8+7+0-:1]) && result[7+0-:1]);
    n = result[7+0-:1];
  end
endmodule
