/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_2 (
    input clk,
    input rst,
    input [23:0] io_dip,
    output reg [23:0] io_led,
    output reg [7:0] led
  );
  
  
  
  wire [8-1:0] M_adder_io_led2;
  wire [1-1:0] M_adder_z;
  wire [1-1:0] M_adder_v;
  wire [1-1:0] M_adder_n;
  add_3 adder (
    .io_dip(io_dip),
    .io_led2(M_adder_io_led2),
    .z(M_adder_z),
    .v(M_adder_v),
    .n(M_adder_n)
  );
  
  wire [8-1:0] M_compare_io_led2;
  compare_4 compare (
    .io_dip(io_dip),
    .io_led2(M_compare_io_led2)
  );
  
  wire [8-1:0] M_boolean_io_led2;
  boolean_5 boolean (
    .io_dip(io_dip),
    .io_led2(M_boolean_io_led2)
  );
  
  wire [8-1:0] M_shift_io_led2;
  shift_6 shift (
    .io_dip(io_dip),
    .io_led2(M_shift_io_led2)
  );
  
  wire [8-1:0] M_muldiv_io_led2;
  muldiv_7 muldiv (
    .io_dip(io_dip),
    .io_led2(M_muldiv_io_led2)
  );
  
  always @* begin
    led = 8'h00;
    io_led[0+7-:8] = io_dip[0+7-:8];
    io_led[8+7-:8] = io_dip[8+7-:8];
    
    case (io_dip[16+4+1-:2])
      1'h0: begin
        if (io_dip[16+0+1-:2] == 1'h0 || io_dip[16+0+1-:2] == 1'h1) begin
          io_led[16+7-:8] = M_adder_io_led2;
          led[0+0-:1] = M_adder_z;
          led[1+0-:1] = M_adder_v;
          led[2+0-:1] = M_adder_n;
        end else begin
          io_led[16+7-:8] = M_muldiv_io_led2;
        end
      end
      1'h1: begin
        io_led[16+7-:8] = M_boolean_io_led2;
      end
      2'h2: begin
        io_led[16+7-:8] = M_shift_io_led2;
      end
      2'h3: begin
        io_led[16+7-:8] = M_compare_io_led2;
      end
    endcase
  end
endmodule
