/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module muldiv_7 (
    input [23:0] io_dip,
    output reg [7:0] io_led2
  );
  
  
  
  always @* begin
    io_led2 = 1'h0;
    
    case (io_dip[16+0+1-:2])
      2'h2: begin
        io_led2 = io_dip[0+7-:8] * io_dip[8+7-:8];
      end
      2'h3: begin
        io_led2 = io_dip[0+7-:8] / io_dip[8+7-:8];
      end
    endcase
  end
endmodule
