/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module testcase_2 (
    input clk,
    input rst,
    output reg [7:0] out,
    output reg [7:0] a,
    output reg [7:0] b
  );
  
  
  
  reg [23:0] io_dip;
  
  
  localparam BEGIN_state = 4'd0;
  localparam ADD_state = 4'd1;
  localparam SUB_state = 4'd2;
  localparam MUL_state = 4'd3;
  localparam DIV_state = 4'd4;
  localparam AND_state = 4'd5;
  localparam OR_state = 4'd6;
  localparam XOR_state = 4'd7;
  localparam A_state = 4'd8;
  localparam SHL_state = 4'd9;
  localparam SHR_state = 4'd10;
  localparam SRA_state = 4'd11;
  localparam CMPEQ_state = 4'd12;
  localparam CMPLE_state = 4'd13;
  localparam CMPLT_state = 4'd14;
  localparam PASS_state = 4'd15;
  
  reg [3:0] M_state_d, M_state_q = BEGIN_state;
  
  wire [1-1:0] M_blink_blink;
  wire [27-1:0] M_blink_hold;
  blink_4 blink (
    .rst(rst),
    .clk(clk),
    .blink(M_blink_blink),
    .hold(M_blink_hold)
  );
  
  wire [24-1:0] M_alu_io_led;
  wire [8-1:0] M_alu_led;
  alu_3 alu (
    .io_dip(io_dip),
    .io_led(M_alu_io_led),
    .led(M_alu_led)
  );
  
  localparam OADD = 6'h00;
  
  localparam OSUB = 6'h01;
  
  localparam OMUL = 6'h02;
  
  localparam ODIV = 6'h03;
  
  localparam OAND = 6'h18;
  
  localparam OOR = 6'h1e;
  
  localparam OXOR = 6'h16;
  
  localparam OA = 6'h1a;
  
  localparam OSHL = 6'h20;
  
  localparam OSHR = 6'h21;
  
  localparam OSRA = 6'h23;
  
  localparam OCMPEQ = 6'h33;
  
  localparam OCMPLT = 6'h35;
  
  localparam OCMPLE = 6'h37;
  
  localparam RADD = 8'h7a;
  
  localparam RSUB = 8'h30;
  
  localparam RMUL = 8'h49;
  
  localparam RDIV = 8'h02;
  
  localparam RAND = 8'h05;
  
  localparam ROR = 8'h75;
  
  localparam RXOR = 8'h70;
  
  localparam RA = 8'h25;
  
  localparam RSHL = 8'ha0;
  
  localparam RSHR = 8'h01;
  
  localparam RSRA = 8'h01;
  
  localparam RCMPEQ = 8'h00;
  
  localparam RCMPLT = 8'h00;
  
  localparam RCMPLE = 8'h00;
  
  localparam A = 8'h55;
  
  localparam B = 8'h25;
  
  always @* begin
    M_state_d = M_state_q;
    
    a = 8'h55;
    b = 8'h25;
    io_dip[8+7-:8] = 8'h55;
    io_dip[0+7-:8] = 8'h25;
    io_dip[16+7-:8] = 1'h0;
    out = 1'h0;
    
    case (M_state_q)
      BEGIN_state: begin
        out[0+0-:1] = M_blink_blink;
        if (M_blink_hold == 1'h1) begin
          M_state_d = ADD_state;
        end
      end
      ADD_state: begin
        io_dip[16+0+5-:6] = 6'h00;
        out[1+0-:1] = M_blink_blink;
        if (M_alu_io_led[16+7-:8] == 8'h7a && M_blink_hold == 1'h1) begin
          M_state_d = SUB_state;
        end
      end
      SUB_state: begin
        io_dip[16+0+5-:6] = 6'h01;
        out[2+0-:1] = M_blink_blink;
        if (M_alu_io_led[16+7-:8] == 8'h30 && M_blink_hold == 1'h1) begin
          M_state_d = MUL_state;
        end
      end
      MUL_state: begin
        io_dip[16+0+5-:6] = 6'h02;
        out[3+0-:1] = M_blink_blink;
        if (M_alu_io_led[16+7-:8] == 8'h49 && M_blink_hold == 1'h1) begin
          M_state_d = DIV_state;
        end
      end
      DIV_state: begin
        io_dip[16+0+5-:6] = 6'h03;
        out[4+0-:1] = M_blink_blink;
        if (M_alu_io_led[16+7-:8] == 8'h02 && M_blink_hold == 1'h1) begin
          M_state_d = AND_state;
        end
      end
      AND_state: begin
        io_dip[16+0+5-:6] = 6'h18;
        out[5+0-:1] = M_blink_blink;
        if (M_alu_io_led[16+7-:8] == 8'h05 && M_blink_hold == 1'h1) begin
          M_state_d = OR_state;
        end
      end
      OR_state: begin
        io_dip[16+0+5-:6] = 6'h1e;
        out[6+0-:1] = M_blink_blink;
        if (M_alu_io_led[16+7-:8] == 8'h75 && M_blink_hold == 1'h1) begin
          M_state_d = XOR_state;
        end
      end
      XOR_state: begin
        io_dip[16+0+5-:6] = 6'h16;
        out[7+0-:1] = M_blink_blink;
        if (M_alu_io_led[16+7-:8] == 8'h70 && M_blink_hold == 1'h1) begin
          M_state_d = A_state;
        end
      end
      A_state: begin
        io_dip[16+0+5-:6] = 6'h1a;
        out[0+0-:1] = M_blink_blink;
        out[1+0-:1] = M_blink_blink;
        if (M_alu_io_led[16+7-:8] == 8'h25 && M_blink_hold == 1'h1) begin
          M_state_d = SHL_state;
        end
      end
      SHL_state: begin
        io_dip[16+0+5-:6] = 6'h20;
        out[0+0-:1] = M_blink_blink;
        out[2+0-:1] = M_blink_blink;
        if (M_alu_io_led[16+7-:8] == 8'ha0 && M_blink_hold == 1'h1) begin
          M_state_d = SHR_state;
        end
      end
      SHR_state: begin
        io_dip[16+0+5-:6] = 6'h21;
        out[0+0-:1] = M_blink_blink;
        out[3+0-:1] = M_blink_blink;
        if (M_alu_io_led[16+7-:8] == 8'h01 && M_blink_hold == 1'h1) begin
          M_state_d = SRA_state;
        end
      end
      SRA_state: begin
        io_dip[16+0+5-:6] = 6'h23;
        out[0+0-:1] = M_blink_blink;
        out[4+0-:1] = M_blink_blink;
        if (M_alu_io_led[16+7-:8] == 8'h01 && M_blink_hold == 1'h1) begin
          M_state_d = CMPEQ_state;
        end
      end
      CMPEQ_state: begin
        io_dip[16+0+5-:6] = 6'h33;
        out[0+0-:1] = M_blink_blink;
        out[5+0-:1] = M_blink_blink;
        if (M_alu_io_led[16+7-:8] == 8'h00 && M_blink_hold == 1'h1) begin
          M_state_d = CMPLE_state;
        end
      end
      CMPLE_state: begin
        io_dip[16+0+5-:6] = 6'h37;
        out[0+0-:1] = M_blink_blink;
        out[6+0-:1] = M_blink_blink;
        if (M_alu_io_led[16+7-:8] == 8'h00 && M_blink_hold == 1'h1) begin
          M_state_d = CMPLT_state;
        end
      end
      CMPLT_state: begin
        io_dip[16+0+5-:6] = 6'h35;
        out[0+0-:1] = M_blink_blink;
        out[7+0-:1] = M_blink_blink;
        if (M_alu_io_led[16+7-:8] == 8'h00 && M_blink_hold == 1'h1) begin
          M_state_d = PASS_state;
        end
      end
      PASS_state: begin
        out = {4'h8{M_blink_blink}};
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
